# https://www.youtube.com/watch?v=35tu6XnRkH0

In [ ]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [ ]:
data ="""microsoft technologies is a leading software development company\n
microsoft technologies provide training to working preofessional an students\n
we are product based and service based company\n
we have one of our office in IT park, Bangalore"""

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data=tokenizer.texts_to_sequences([data])[0]
encoded_data

[1,
 2,
 6,
 7,
 8,
 9,
 10,
 3,
 1,
 2,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 4,
 18,
 19,
 5,
 20,
 21,
 5,
 3,
 4,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30]

In [ ]:
# determine the vocabulary size
vocab_size=len(tokenizer.word_index)+1
vocab_size

31

In [ ]:
# training data one word input, one word as output
sequences = list()
for i in range(1, len(encoded_data)):

  sequence=encoded_data[i-1:i+1]
  sequences.append(sequence)
len(sequences)

34

In [ ]:
sequences

[[1, 2],
 [2, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [10, 3],
 [3, 1],
 [1, 2],
 [2, 11],
 [11, 12],
 [12, 13],
 [13, 14],
 [14, 15],
 [15, 16],
 [16, 17],
 [17, 4],
 [4, 18],
 [18, 19],
 [19, 5],
 [5, 20],
 [20, 21],
 [21, 5],
 [5, 3],
 [3, 4],
 [4, 22],
 [22, 23],
 [23, 24],
 [24, 25],
 [25, 26],
 [26, 27],
 [27, 28],
 [28, 29],
 [29, 30]]

In [ ]:
sequences=array(sequences)
X,y=sequences[:,0],sequences[:,1]

In [ ]:
X[:5]

array([1, 2, 6, 7, 8])

In [ ]:
y[:5]

array([2, 6, 7, 8, 9])

In [ ]:
y=to_categorical(y,num_classes=vocab_size)
y[:5]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [ ]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1, 10)             310       
                                                                 
 lstm (LSTM)                 (None, 50)                12200     
                                                                 
 dense (Dense)               (None, 31)                1581      
                                                                 
Total params: 14,091
Trainable params: 14,091
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=20)

Epoch 1/20
2/2 [==============================] - 3s 12ms/step - loss: 3.4338 - accuracy: 0.0294
Epoch 2/20
2/2 [==============================] - 0s 9ms/step - loss: 3.4328 - accuracy: 0.0882
Epoch 3/20
2/2 [==============================] - 0s 11ms/step - loss: 3.4321 - accuracy: 0.1176
Epoch 4/20
2/2 [==============================] - 0s 17ms/step - loss: 3.4314 - accuracy: 0.1176
Epoch 5/20
2/2 [==============================] - 0s 12ms/step - loss: 3.4308 - accuracy: 0.1176
Epoch 6/20
2/2 [==============================] - 0s 13ms/step - loss: 3.4302 - accuracy: 0.1471
Epoch 7/20
2/2 [==============================] - 0s 12ms/step - loss: 3.4297 - accuracy: 0.1471
Epoch 8/20
2/2 [==============================] - 0s 11ms/step - loss: 3.4291 - accuracy: 0.1471
Epoch 9/20
2/2 [==============================] - 0s 12ms/step - loss: 3.4286 - accuracy: 0.1176
Epoch 10/20
2/2 [==============================] - 0s 13ms/step - loss: 3.4280 - accuracy: 0.1176
Epoch 11/20
2/2 [=============

In [ ]:
def generate_seq(model, tokenizer, enter_text,n_pred):
  in_text,result=enter_text,enter_text
  for _ in range(n_pred):
    encoded=tokenizer.texts_to_sequences([in_text])[0]
    encoded=array(encoded)

    predict_x=model.predict(encoded)
    yhat=np.argmax(predict_x,axis=1)
    out_word=''
    for word,index in tokenizer.word_index.items():
      if index==yhat:
        out_word=word
        break
    in_text,result=out_word,result+ ' '+out_word
  return result

In [ ]:
import numpy as np
print(generate_seq(model,tokenizer,'microsoft',6))

microsoft based company based company based company


In [ ]:
print(generate_seq(model,tokenizer,'service',6))

service based company based company based company
